---
title: "a3_task3_caroline_shepherd"
author: "Caroline Shepherd"
date: "10/27/2021"
output: 
  html_document: 
    toc: yes
    theme: cerulean
    code_folding: hide
---

## Setup

```{r setup, include=FALSE, warnings = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Attach packages

```{r}
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
library(dplyr)
```

## Read in the data

```{r}
urchins <- read_csv(here("data", "urchins.csv"))

## Clean names

urchins_clean <- urchins %>% 
  clean_names()
```

## Visualize the data

```{r}
ggplot(data = urchins_clean, aes(x = size)) + # Create ggplot
  geom_histogram(bins = 10) + # Change number of bins from default to 10
  facet_wrap(~ common_name) + # Facet wrap by common name to sort Purple and Red Sea Urchins
  labs(x = "Number of Urchins", # Change titles
       y = "Size of Urchins (cm)",
       title = "Size (cm) and Amount of Purple and Red Sea Urchins")
```

#### Figure 1.0 Depicts the number and size of sea urchins, grouped by species - Red or Purple Sea Urchins
  

#### Table 1.0 Depicts the statistical analysis of Sea Urchin Size (cm), grouped by species of Red or Purple Sea Urchins
```{r}
urchin_stats <- urchins_clean %>%  # Name new vector
  group_by(common_name) %>%  # Group by species
  summarize(mean_urchins = mean(size), # Use summarize to find several statistics 
            median_urchins = median(size),
            sd_urchins = sd(size),
            sample_size = n()) %>% 
   rename("Common Name" = common_name, # Rename table names for clarity
         "Mean Sea Urchin Size (cm)" = mean_urchins,
         "Median Sea Urchan Size (cm)" = median_urchins,
         "Standard Deviation of Sea Urchin Size (cm)" = sd_urchins,
         "Amount of Sea Urchins Sampled" = sample_size)

urchin_stats %>% 
  kbl(caption = "Statistical Analysis of Sea Urchin Size (cm), Grouped by Species") %>% 
  kable_styling(top_gap,
                caption = "Table 1.0 Depicts the statistical analysis of Sea Urchin Size (cm), grouped by species")
```



